library(data.table)
library(tidyverse)

sal_usa <-  read.csv("~/Brown University/PHP_2550/Data/updated_salmonella_US.csv")
dim(sal_usa) #297222     21
length(unique(sal_usa$Isolation.source)) #3779
sal_usa$Isolation.source = tolower(sal_usa$Isolation.source)
sal_usa$Isolation.source.category <- sal_usa$Isolation.source

sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "milk" == TRUE] <- "Dairy"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "cream" == TRUE] <- "Dairy"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "cheese" == TRUE] <- "Dairy"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "whey" == TRUE] <- "Dairy"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "dairy" == TRUE] <- "Dairy"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "yogurt" == TRUE] <- "Dairy"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "egg" == TRUE] <- "Dairy"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "butter" == TRUE] <- "Dairy"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "yolk" == TRUE] <- "Dairy"


sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "chick feed" == TRUE] <- "Poultry"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "gallus gallus" == TRUE] <- "Poultry"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "chicken" == TRUE] <- "Poultry"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "wing" == TRUE] <- "Poultry"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "broiler carcass" == TRUE] <- "Poultry"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "drag swab"] <- "Poultry"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "duck" == TRUE] <- "Poultry"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "goose" == TRUE] <- "Poultry"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "poultry" == TRUE] <- "Poultry"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "avian" == TRUE] <- "Poultry"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "turkey" == TRUE] <- "Poultry"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "meleagris gallopav" == TRUE] <- "Poultry"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "cicken" == TRUE] <- "Poultry"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "chicekn" == TRUE] <- "Poultry"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "chkn" == TRUE] <- "Poultry"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "melagris" == TRUE] <- "Poultry"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "gizzard" == TRUE] <- "Poultry"


sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "pork" == TRUE] <- "Pig"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "sausage" == TRUE] <- "Pig"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "salami" == TRUE] <- "Pig"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "pig" == TRUE] <- "Pig"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "swine" == TRUE] <- "Pig"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "porcine" == TRUE] <- "Pig"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "sus scrofa" == TRUE] <- "Pig"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "sus domesticus" == TRUE] <- "Pig"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "hog" == TRUE] <- "Pig"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "sow" == TRUE] <- "Pig"


sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "beef" == TRUE] <- "Cattle"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "cow" == TRUE] <- "Cattle"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "bos taurus" == TRUE] <- "Cattle"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "cattle" == TRUE] <- "Cattle"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "bovine" == TRUE] <- "Cattle"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "calf" == TRUE] <- "Cattle"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "heifer" == TRUE] <- "Cattle"

sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "felis catus" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "dog" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "cat" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "feline" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "canine" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "pet" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "litter" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "lupus" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "kennel" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "kibble" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "fish" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "shrimp" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "salmon" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "clam" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "jambalaya" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "tuna" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "crab" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "oyster" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "fillet" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "lamb" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "ovine" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "goat" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "sheep" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "ovis" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "rabbit" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "horse" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "lama glama" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "kangaroo" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "camel" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "llama" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "alpaca" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "equus caballus" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "equine" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "moose" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "elk" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "deer" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "raccoon" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "brown" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "monkey" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "mouse" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "hamster" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "rodent" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "turtle" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "sea lion" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "tortoise" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "neovison vison" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "enhydra" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "marine mammal" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "siluriformes" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "hip" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "bird" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "pigeon" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "quail" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "seagull" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "parrot" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "sparrow" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "eudocimus albus" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "owl" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "bat" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "emu" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "pogona" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "snake" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "pantherophis guttatus" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "python" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "reptilia" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "chamelion" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "dragon" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "lizard" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "reptile" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "sistrurus miliarius" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "alligator" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "iguana" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "mink" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "gull" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "heron" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "marsupial" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "boa" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "feed" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "zebra" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "animal"] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "wild mammal" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "finch" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "crane" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "giraffe" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "sponge" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "panthera" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "frog" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "alces" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "cervid" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "dried meat"] <-"Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "meat"] <-"Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "meat mixture"] <-"Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "trim meat"] <-"Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "meat trim"] <-"Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "finished meat product"] <-"Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "meat patty"] <-"Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "raw meat"] <-"Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "finished meat"] <-"Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "raw meat swab"] <-"Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "animal stool"] <-"Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "caballus" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "capra" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "opossum" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "perch" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "eagle" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "godwit" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "cormorant" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "grebe" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "bison" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "hawk" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "crossbill" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "dove" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "pelican" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "american coot (fulica americana)" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "veal" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "buffalo" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "isolated organism"] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "carcass swab"] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "raw bone"] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "opposum"] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category %like% "pheasant" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category %like% "gecko" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category %like% "equus" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category %like% "antelope" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category %like% "chinchilla" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category %like% "cardinal" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category %like% "egret" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category %like% "vulture" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category %like% "hydroprogne" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category %like% "odocoileus" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category %like% "gallus" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category %like% "ibis" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category %like% "armadillo" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category %like% "parakeet" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "animal isolate, animal stool"] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category %like% "eclectus" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category %like% "fulica" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category %like% "falco" == TRUE] <- "Animal(Other)"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category %like% "donkey" == TRUE] <- "Animal(Other)"


sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "hay"] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "packaging" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "house" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "bedding" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "compost" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "air" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "sediment" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "tank" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "pond" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "river" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "soil" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "floor" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "rinse water" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "irrigation" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "forest" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "unit" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "aquarium" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "reservoir" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "ground" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "room" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "lake" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "water" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "wall" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "vacuum" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "stage" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "ocean" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "door" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "creek" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "vent" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "farm" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "forest" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "barn" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "metal" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "sewage" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "environment" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "fertilizer" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "dryer" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "stream" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "surface" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "lagoon" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "truck" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "fence" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "restaurant" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "fan" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "manure belt" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "manure"] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "plate" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "tray" == TRUE] <- "Environment"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "box" == TRUE] <- "Environment"


sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "oregano" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "basil" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "paprika" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "rosemary" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "tri pepper mixture" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "powder" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "thyme" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "cumin" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "sage" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "spice" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "soy" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "bean" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "legume" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "tempeh" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "lettuce" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "kale" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "spinach" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "leaf" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "lolla rosa" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "salad" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "sprout" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "cabbage" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "mushroom" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "pepper" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "cucumber" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "asparagus" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "celery" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "corn" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "pea" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "radish" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "chard" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "fresh parsley" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "cilantro" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "coriander" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "veget" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "onion" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "ginger" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "kratom" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "arugula" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "parsley" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "potato" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "strawberry" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "lemon" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "lime" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "papaya" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "mango" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "cantaloupe" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "avocado" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "tomato" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "blueberry" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "grape" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "fruit" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "apple" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "produce" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "broccoli" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "carrot" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "fenugreek" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "xanthum" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "olive" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "chia" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "zucchini" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "cardamom" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "romaine" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "raddish" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "garlic" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "cinnamon" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "leafy" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "greens" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "pamillo" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "alfalfa" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "bok choy" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "field red pack choi" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "wheat" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "rice" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "oat" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "cereal" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "food" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "guacamole" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "cuisine" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "asian" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "bread" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "grain" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "almond" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "nut" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "seed" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "pecan" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "pistachio" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "cashew" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "chaoli" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "canola" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "meal" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "cake" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "honey" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "chocolate" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "sugar" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "candy" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "marshmallow" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "fluff" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "juice" == TRUE] <- "Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "tea" == TRUE] <-"Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "pesto" == TRUE] <-"Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "ready" == TRUE] <-"Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "raw food" == TRUE] <-"Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "mayo" == TRUE] <-"Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "biscuit" == TRUE] <-"Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "burger" == TRUE] <-"Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "natural and artificial vanilla" == TRUE] <-"Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "lunch" == TRUE] <-"Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "hummus" == TRUE] <-"Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "roast" == TRUE] <-"Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "nonmeat-other"] <-"Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "barbeque"] <-"Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "meat"] <-"Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "tahini"] <-"Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category %like% "flour" == TRUE] <-"Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "dietary" == TRUE] <-"Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "broth"] <-"Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "supplement"] <-"Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "pot pie"] <-"Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "cookie" == TRUE] <-"Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "lasagna"] <-"Produce and Food"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "enchilada"] <-"Produce and Food"


sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "caecum" == TRUE] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "cloacal swab" == TRUE] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "human" == TRUE] <- "Human"
sal_usa$Isolation.source.category[tolower(sal_usa$Isolation.source.category) == "liver"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "intestine"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "urine"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "person" == TRUE] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "colon"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "spleen"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category ==  "child"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "vagina" == TRUE] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "nasal" == TRUE] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "newborn" == TRUE] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "skin" == TRUE] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "neck" == TRUE] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "nasopharyngeal" == TRUE] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "lymph" == TRUE] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "aneurysm sac" == TRUE] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "bile" == TRUE] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "gall bladder" == TRUE] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "rectal" == TRUE] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "clinical" == TRUE] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category%like% "biological fluid or and tissue" == TRUE] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "blood"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "swab"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "stool"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "feces"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "wound"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "chest"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "blood culture"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "ear"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "oral"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "abdominal"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "scrotum"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "cyst"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "breast fluid"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "toe"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "abcess"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category %like% "patient" == TRUE] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "fluid"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "buttock"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "sinus"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "fluid"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category %like% "lung" == TRUE] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "rectum"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "body"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "uterus"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "colon, intest"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "thighs"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "genital"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "perineum"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "breast"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "breasts"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "anal"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "groin"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category %like% "gallbladder" == TRUE] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "saliva"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "abscess"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "tissue"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "small intestine"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "autopsy"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "kidney"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "urethral"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "intestinal"] <- "Human"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "whole blood"] <- "Human"

sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "not collected"] <- "Missing and Other"
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == "raw product"] <- "Missing and Other"




length(unique(sal_usa$Isolation.source.category)) #335
unique(sal_usa$Isolation.source.category)

x <- as.data.frame(table(sal_usa$Isolation.source.category))
x %>% filter(Freq >= 50)

# Missing and other group created (Other accounts for 1150, missing counts for 184242)
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category == ""] <- "Missing and Other"

# Sources with frequency less than 50 grouped as Missing and Other
created = c("Pig", "Poultry", "Cattle", "Animal(Other)", "Produce and Food", "Human", "Environment", "Missing and Other")
sal_usa$Isolation.source.category[sal_usa$Isolation.source.category %in% created == FALSE] <- "Missing and Other"
y <- as.data.frame(table(sal_usa$Isolation.source.category))
y %>% filter(Freq >= 50)

write.csv(sal_usa,"final_source_salmonella.csv", row.names = FALSE)
