## This is a code for PHP 2550 at Brown University SPH, the purpose is to 
## clean location that have different format e.g some are two letters state
## abbreviation, some are full state names or some are the big cities name
## without the state name. To account for this heterogenity, we preprocess
## the data here.

library(data.table)

#load the data
campylobacter_dat <- read.csv("Campylobacter_13to22.csv")
dim(campylobacter_dat) #59507    21

#extract only US cases
campylobacter_us <- campylobacter_dat[campylobacter_dat$Location %like% "US", ]
dim(campylobacter_us) # 44949    21

campylobacter_us$Location[campylobacter_us$Location %like% "USA:NC"== TRUE] <- "NC"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: NC"== TRUE] <- "NC"
campylobacter_us$Location[campylobacter_us$Location %like% "North Carolina"== TRUE] <- "NC"
campylobacter_us$Location[campylobacter_us$Location %like% "PA"== TRUE] <- "PA"
campylobacter_us$Location[campylobacter_us$Location %like% "Philadelphia" == TRUE] <- "PA"
campylobacter_us$Location[campylobacter_us$Location %like% "Pennsylvania" == TRUE] <- "PA"
campylobacter_us$Location[campylobacter_us$Location %like% "GA" == TRUE] <- "GA"
campylobacter_us$Location[campylobacter_us$Location %like% "Georgia" == TRUE] <- "GA"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:AL" == TRUE] <- "AL"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: AL" == TRUE] <- "AL"
campylobacter_us$Location[campylobacter_us$Location %like% "Alabama" == TRUE] <- "AL"
campylobacter_us$Location[campylobacter_us$Location %like% "SC" == TRUE] <- "SC"
campylobacter_us$Location[campylobacter_us$Location %like% "SD" == TRUE] <- "SD"
campylobacter_us$Location[campylobacter_us$Location %like% "IA" == TRUE] <- "IA"
campylobacter_us$Location[campylobacter_us$Location %like% "Iowa" == TRUE] <- "IA"
campylobacter_us$Location[campylobacter_us$Location %like% "TN" == TRUE] <- "TN"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:CO" == TRUE] <- "CO"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: CO" == TRUE] <- "CO"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: Aurora, CO" == TRUE] <- "CO"
campylobacter_us$Location[campylobacter_us$Location %like% "Colorado" == TRUE] <- "CO"
campylobacter_us$Location[campylobacter_us$Location %like% "MS" == TRUE] <- "MS"
campylobacter_us$Location[campylobacter_us$Location %like% "Mississippi" == TRUE] <- "MS"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: CA" == TRUE] <- "CA"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:CA" == TRUE] <- "CA"
campylobacter_us$Location[campylobacter_us$Location %like% "San Diego" == TRUE] <- "CA"
campylobacter_us$Location[campylobacter_us$Location %like% "San Francisco" == TRUE] <- "CA"
campylobacter_us$Location[campylobacter_us$Location %like% "California" == TRUE] <- "CA"
campylobacter_us$Location[campylobacter_us$Location %like% "Davis" == TRUE] <- "CA"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:GU" == TRUE] <- "GU"
campylobacter_us$Location[campylobacter_us$Location %like% "VA" == TRUE] <- "VA"
campylobacter_us$Location[campylobacter_us$Location %like% "Virginia" == TRUE] <- "VA"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:DE" == TRUE] <- "DE"
campylobacter_us$Location[campylobacter_us$Location %like% "Delaware" == TRUE] <- "DE"
campylobacter_us$Location[campylobacter_us$Location %like% "TX" == TRUE] <- "TX"
campylobacter_us$Location[campylobacter_us$Location %like% "Texas" == TRUE] <- "TX"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:WA" == TRUE] <- "WA"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: WA" == TRUE] <- "WA"
campylobacter_us$Location[campylobacter_us$Location %like% "Washington" == TRUE] <- "WA"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:OH" == TRUE] <- "OH"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: OH" == TRUE] <- "OH"
campylobacter_us$Location[campylobacter_us$Location %like% "Ohio" == TRUE] <-"OH"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:WI" == TRUE] <- "WI"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: WI" == TRUE] <- "WI"
campylobacter_us$Location[campylobacter_us$Location %like% "Wisconsin" == TRUE] <- "WI"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:KY" == TRUE] <- "KY"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: KY" == TRUE] <- "KY"
campylobacter_us$Location[campylobacter_us$Location %like% "Kentucky" == TRUE] <- "KY"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:MD" == TRUE] <- "MD"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: MD" == TRUE] <- "MD"
campylobacter_us$Location[campylobacter_us$Location %like% "AZ" == TRUE] <- "AZ"
campylobacter_us$Location[campylobacter_us$Location %like% "Arizona" == TRUE] <- "AZ"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:MI" == TRUE] <- "MI"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: MI" == TRUE] <- "MI"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:Mi" == TRUE] <- "MI"
campylobacter_us$Location[campylobacter_us$Location %like% "Michigan" == TRUE] <- "MI"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:FL" == TRUE] <- "FL"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: FL" == TRUE] <- "FL"
campylobacter_us$Location[campylobacter_us$Location %like% "Florida" == TRUE] <- "FL"
campylobacter_us$Location[campylobacter_us$Location %like% "NJ" == TRUE] <- "NJ"
campylobacter_us$Location[campylobacter_us$Location %like% "New Jersey" == TRUE] <- "NJ"
campylobacter_us$Location[campylobacter_us$Location %like% "New Jersy" == TRUE] <- "NJ"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:IN" == TRUE] <- "IN"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: IN" == TRUE] <- "IN"
campylobacter_us$Location[campylobacter_us$Location %like% "Indiana" == TRUE] <- "IN"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:MA" == TRUE] <- "MA"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: MA" == TRUE] <- "MA"
campylobacter_us$Location[campylobacter_us$Location %like% "Boston" == TRUE] <- "MA"
campylobacter_us$Location[campylobacter_us$Location %like% "Massachusetts" == TRUE] <- "MA"
campylobacter_us$Location[campylobacter_us$Location %like% "Maryland" == TRUE] <- "MA"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:NY" == TRUE] <- "NY"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: NY" == TRUE] <- "NY"
campylobacter_us$Location[campylobacter_us$Location %like% "New York" == TRUE] <- "NY"
campylobacter_us$Location[campylobacter_us$Location %like% "OK" == TRUE] <- "OK"
campylobacter_us$Location[campylobacter_us$Location %like% "Oklahoma" == TRUE] <- "OK"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: NE" == TRUE] <- "NE"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:NE" == TRUE] <- "NE"
campylobacter_us$Location[campylobacter_us$Location %like% "Nebraska" == TRUE] <- "NE"
campylobacter_us$Location[campylobacter_us$Location %like% "WV" == TRUE] <- "WV"
campylobacter_us$Location[campylobacter_us$Location %like% "UT" == TRUE] <- "UT"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:IL" == TRUE] <- "IL"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: IL" == TRUE] <- "IL"
campylobacter_us$Location[campylobacter_us$Location %like% "Illinois" == TRUE] <- "IL"
campylobacter_us$Location[campylobacter_us$Location %like% "KS" == TRUE] <- "KS"
campylobacter_us$Location[campylobacter_us$Location %like% "Kansas" == TRUE] <- "KS"
campylobacter_us$Location[campylobacter_us$Location %like% "MO" == TRUE] <- "MO"
campylobacter_us$Location[campylobacter_us$Location %like% "Missouri" == TRUE] <- "MO"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:RI" == TRUE] <- "RI"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: RI" == TRUE] <- "RI"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: ID" == TRUE] <- "ID"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:ID" == TRUE] <- "ID"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:AR" == TRUE] <- "AR"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: AR" == TRUE] <- "AR"
campylobacter_us$Location[campylobacter_us$Location %like% "Arkansas" == TRUE] <- "AR"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:MN" == TRUE] <- "MN"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: MN" == TRUE] <- "MN"
campylobacter_us$Location[campylobacter_us$Location %like% "Minnesota" == TRUE] <- "MS"
campylobacter_us$Location[campylobacter_us$Location %like% "Minneapolis" == TRUE] <- "MS"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:LA" == TRUE] <- "LA"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: LA" == TRUE] <- "LA"
campylobacter_us$Location[campylobacter_us$Location %like% "Louisiana" == TRUE] <- "LA"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:NM" == TRUE] <- "NM"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: NM" == TRUE] <- "NM"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:AL" == TRUE] <- "AL"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:ME" == TRUE] <- "ME"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: ME" == TRUE] <- "ME"
campylobacter_us$Location[campylobacter_us$Location %like% "Maine" == TRUE] <- "ME"
campylobacter_us$Location[campylobacter_us$Location %like% "VT" == TRUE] <- "VT"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: HI" == TRUE] <- "HI"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:HI" == TRUE] <- "HI"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:CT" == TRUE] <- "CT"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: CT" == TRUE] <- "CT"
campylobacter_us$Location[campylobacter_us$Location %like% "Connecticut" == TRUE] <- "CT"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:PR" == TRUE] <- "PR"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:ND" == TRUE] <- "ND"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: ND" == TRUE] <- "ND"
campylobacter_us$Location[campylobacter_us$Location %like% "North Dakota" == TRUE] <- "ND"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:OR" == TRUE] <- "OR"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: OR" == TRUE] <- "OR"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: or" == TRUE] <- "OR"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:or" == TRUE] <- "OR"
campylobacter_us$Location[campylobacter_us$Location %like% "Oregon" == TRUE] <- "OR"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:NH" == TRUE] <- "NH"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: NH" == TRUE] <- "NH"
campylobacter_us$Location[campylobacter_us$Location %like% "New Hampshire" == TRUE] <- "NH"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:WY" == TRUE] <- "WY"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: WY" == TRUE] <- "WY"
campylobacter_us$Location[campylobacter_us$Location %like% "NV" == TRUE] <- "NV"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:DC" == TRUE] <- "DC"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: Washington DC" == TRUE] <- "DC"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:State" == TRUE] <- "DC"
campylobacter_us$Location[campylobacter_us$Location %like% "Midwest" == TRUE] <- "Midwest"
campylobacter_us$Location[campylobacter_us$Location %like% "MidWest" == TRUE] <- "Midwest"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:AK" == TRUE] <- "AK"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:MT" == TRUE] <- "MT"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:MW" == TRUE] <- "MW"
campylobacter_us$Location[campylobacter_us$Location %like% "Lansing" == TRUE] <- "MI"
campylobacter_us$Location[campylobacter_us$Location %like% "Gainesville" == TRUE] <- "FL"
campylobacter_us$Location[campylobacter_us$Location %like% "Tulsa" == TRUE] <- "OK"
campylobacter_us$Location[campylobacter_us$Location %like% "Western Region" == TRUE] <- "Western Region"
campylobacter_us$Location[campylobacter_us$Location %like% "region 9" == TRUE] <- "HHS region 9"
campylobacter_us$Location[campylobacter_us$Location %like% "Chicago" == TRUE] <- "IL"
campylobacter_us$Location[campylobacter_us$Location %like% ", CA" == TRUE] <- "CA"
campylobacter_us$Location[campylobacter_us$Location %like% ", NY" == TRUE] <- "NY"
campylobacter_us$Location[campylobacter_us$Location %like% ", CO" == TRUE] <- "CO"
campylobacter_us$Location[campylobacter_us$Location %like% ", NC" == TRUE] <- "NC"
campylobacter_us$Location[campylobacter_us$Location %like% "Bethesda" == TRUE] <- "MD"
campylobacter_us$Location[campylobacter_us$Location %like% "District of Columbia" == TRUE] <- "DC"
campylobacter_us$Location[campylobacter_us$Location %like% "Alaska" == TRUE] <- "AK"
campylobacter_us$Location[campylobacter_us$Location %like% "St. Louis" == TRUE] <- "MO"
campylobacter_us$Location[campylobacter_us$Location %like% "Utah" == TRUE] <- "UT"
campylobacter_us$Location[campylobacter_us$Location %like% "Houston" == TRUE] <- "TX"
campylobacter_us$Location[campylobacter_us$Location %like% "Tennessee" == TRUE] <- "TN"
campylobacter_us$Location[campylobacter_us$Location %like% "Califronia" == TRUE] <- "CA"
campylobacter_us$Location[campylobacter_us$Location %like% "Baltimore" == TRUE] <- "MD"
campylobacter_us$Location[campylobacter_us$Location %like% "Seattle" == TRUE] <- "WA"
campylobacter_us$Location[campylobacter_us$Location %like% ", MN" == TRUE] <- "MN"
campylobacter_us$Location[campylobacter_us$Location %like% ", WI" == TRUE] <- "WI"
campylobacter_us$Location[campylobacter_us$Location %like% ", OH" == TRUE] <- "OH"
campylobacter_us$Location[campylobacter_us$Location %like% ", IL" == TRUE] <- "IL"
campylobacter_us$Location[campylobacter_us$Location %like% ", MD" == TRUE] <- "MD"
campylobacter_us$Location[campylobacter_us$Location %like% ", IN" == TRUE] <- "IN"
campylobacter_us$Location[campylobacter_us$Location %like% ", NE" == TRUE] <- "NE"
campylobacter_us$Location[campylobacter_us$Location %like% ", FL" == TRUE] <- "FL"
campylobacter_us$Location[campylobacter_us$Location %like% ", MA" == TRUE] <- "MA"
campylobacter_us$Location[campylobacter_us$Location %like% ",WA" == TRUE] <- "WA"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: DC" == TRUE] <- "DC"
campylobacter_us$Location[campylobacter_us$Location %like% "Ann Arbor" == TRUE] <- "MI"
campylobacter_us$Location[campylobacter_us$Location %like% "Los Angeles" == TRUE] <- "CA"
campylobacter_us$Location[campylobacter_us$Location %like% "Atlanta" == TRUE] <- "GA"
campylobacter_us$Location[campylobacter_us$Location %like% ", ID" == TRUE] <- "ID"
campylobacter_us$Location[campylobacter_us$Location %like% "UCLA" == TRUE] <- "CA"
campylobacter_us$Location[campylobacter_us$Location %like% ", MI" == TRUE] <- "MI"
campylobacter_us$Location[campylobacter_us$Location %like% "St Louis" == TRUE] <- "MO"
campylobacter_us$Location[campylobacter_us$Location %like% "UCSB" == TRUE] <- "CA"
campylobacter_us$Location[campylobacter_us$Location %like% "Rhode" == TRUE] <- "RI"
campylobacter_us$Location[campylobacter_us$Location %like% ", WI" == TRUE] <- "WI"
campylobacter_us$Location[campylobacter_us$Location %like% "South Dakota" == TRUE] <- "SD"
campylobacter_us$Location[campylobacter_us$Location %like% "Sacramento" == TRUE] <- "CA"
campylobacter_us$Location[campylobacter_us$Location %like% "Montana" == TRUE] <- "MT"
campylobacter_us$Location[campylobacter_us$Location %like% "South Central" == TRUE] <- "South Central"
campylobacter_us$Location[campylobacter_us$Location %like% "USA:West" == TRUE] <- "West"
campylobacter_us$Location[campylobacter_us$Location %like% "Montana" == TRUE] <- "MT"
campylobacter_us$Location[campylobacter_us$Location %like% "Nevada" == TRUE] <- "NV"
campylobacter_us$Location[campylobacter_us$Location %like% "New Mexico" == TRUE] <- "NM"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: South" == TRUE] <- "South"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: West" == TRUE] <- "West"
campylobacter_us$Location[campylobacter_us$Location %like% "Pittsburgh" == TRUE] <- "PA"
campylobacter_us$Location[campylobacter_us$Location %like% "Pacific Northwest" == TRUE] <- "Pacific Northwest"
campylobacter_us$Location[campylobacter_us$Location %like% "Miami" == TRUE] <- "FL"
campylobacter_us$Location[campylobacter_us$Location %like% "Cincinnati" == TRUE] <- "OH"
campylobacter_us$Location[campylobacter_us$Location %like% "Palo Alto" == TRUE] <- "CA"
campylobacter_us$Location[campylobacter_us$Location %like% "Alachua" == TRUE] <- "FL"
campylobacter_us$Location[campylobacter_us$Location %like% "Menlo Park" == TRUE] <- "CA"
campylobacter_us$Location[campylobacter_us$Location %like% "Lahey Hospital" == TRUE] <- "MA"
campylobacter_us$Location[campylobacter_us$Location %like% "midwest" == TRUE] <- "Midwest"
campylobacter_us$Location[campylobacter_us$Location %like% "USA: West" == TRUE] <- "West"
campylobacter_us$Location[campylobacter_us$Location %like% "Northeast" == TRUE] <- "Northeast"
campylobacter_us$Location[campylobacter_us$Location %like% "Wood Johnson" == TRUE] <- "NJ"
campylobacter_us$Location[campylobacter_us$Location %like% "Western States" == TRUE] <- "West"
campylobacter_us$Location[campylobacter_us$Location %like% "Walnut Creek" == TRUE] <- "CA"
campylobacter_us$Location[campylobacter_us$Location %like% "Idaho" == TRUE] <- "ID"
campylobacter_us$Location[campylobacter_us$Location %like% "San Antonio" == TRUE] <- "TX"
campylobacter_us$Location[campylobacter_us$Location %like% "Caguas" == TRUE] <- "PR"
campylobacter_us$Location[campylobacter_us$Location %like% "Burlington" == TRUE] <- "VT"
campylobacter_us$Location[campylobacter_us$Location %like% "Milwaukee" == TRUE] <- "WI"
campylobacter_us$Location[campylobacter_us$Location %like% "Lafayette" == TRUE] <- "LA"
campylobacter_us$Location[campylobacter_us$Location %like% "Cambridge" == TRUE] <- "MA"
campylobacter_us$Location[campylobacter_us$Location %like% "Moscow" == TRUE] <- "ID"
campylobacter_us$Location[campylobacter_us$Location %like% ": AK" == TRUE] <- "AK"
campylobacter_us$Location[campylobacter_us$Location %like% "Tucson" == TRUE] <- "AZ"
campylobacter_us$Location[campylobacter_us$Location %like% ", DE" == TRUE] <- "DE"
campylobacter_us$Location[campylobacter_us$Location %like% "Albany CA" == TRUE] <- "CA"
campylobacter_us$Location[campylobacter_us$Location %like% "Fayetteville" == TRUE] <- "CA"
campylobacter_us$Location[campylobacter_us$Location %like% "Lubbock" == TRUE] <- "TX"

unique(campylobacter_us$Location)


