library(data.table)

#load the data
ecoli_dat <- read.csv("E.coli_2013to2022.csv")
dim(ecoli_dat) #111203     21

#extract only US cases
ecoli_us <- ecoli_dat[ecoli_dat$Location %like% "US", ]
dim(ecoli_us) # 34805    21

#clean for location
ecoli_us$Location[ecoli_us$Location %like% "USA:NC"== TRUE] <- "NC"
ecoli_us$Location[ecoli_us$Location %like% "USA: NC"== TRUE] <- "NC"
ecoli_us$Location[ecoli_us$Location %like% "North Carolina"== TRUE] <- "NC"
ecoli_us$Location[ecoli_us$Location %like% "PA"== TRUE] <- "PA"
ecoli_us$Locatione[ecoli_us$Location %like% "Philadelphia" == TRUE] <- "PA"
ecoli_us$Location[ecoli_us$Location %like% "Pennsylvania" == TRUE] <- "PA"
ecoli_us$Location[ecoli_us$Location %like% "GA" == TRUE] <- "GA"
ecoli_us$Location[ecoli_us$Location %like% "Georgia" == TRUE] <- "GA"
ecoli_us$Location[ecoli_us$Location %like% "USA:AL" == TRUE] <- "AL"
ecoli_us$Location[ecoli_us$Location %like% "USA: AL" == TRUE] <- "AL"
ecoli_us$Location[ecoli_us$Location %like% "Alabama" == TRUE] <- "AL"
ecoli_us$Location[ecoli_us$Location %like% "SC" == TRUE] <- "SC"
ecoli_us$Location[ecoli_us$Location %like% "SD" == TRUE] <- "SD"
ecoli_us$Location[ecoli_us$Location %like% "IA" == TRUE] <- "IA"
ecoli_us$Location[ecoli_us$Location %like% "Iowa" == TRUE] <- "IA"
ecoli_us$Location[ecoli_us$Location %like% "TN" == TRUE] <- "TN"
ecoli_us$Location[ecoli_us$Location %like% "USA:CO" == TRUE] <- "CO"
ecoli_us$Location[ecoli_us$Location %like% "USA: CO" == TRUE] <- "CO"
ecoli_us$Location[ecoli_us$Location %like% "USA: Aurora, CO" == TRUE] <- "CO"
ecoli_us$Location[ecoli_us$Location %like% "Colorado" == TRUE] <- "CO"
ecoli_us$Location[ecoli_us$Location %like% "MS" == TRUE] <- "MS"
ecoli_us$Location[ecoli_us$Location %like% "Mississippi" == TRUE] <- "MS"
ecoli_us$Location[ecoli_us$Location %like% "USA: CA" == TRUE] <- "CA"
ecoli_us$Location[ecoli_us$Location %like% "USA:CA" == TRUE] <- "CA"
ecoli_us$Location[ecoli_us$Location %like% "San Diego" == TRUE] <- "CA"
ecoli_us$Location[ecoli_us$Location %like% "San Francisco" == TRUE] <- "CA"
ecoli_us$Location[ecoli_us$Location %like% "California" == TRUE] <- "CA"
ecoli_us$Location[ecoli_us$Location %like% "Davis" == TRUE] <- "CA"
ecoli_us$Location[ecoli_us$Location %like% "USA:GU" == TRUE] <- "GU"
ecoli_us$Location[ecoli_us$Location %like% "VA" == TRUE] <- "VA"
ecoli_us$Location[ecoli_us$Location %like% "Virginia" == TRUE] <- "VA"
ecoli_us$Location[ecoli_us$Location %like% "USA:DE" == TRUE] <- "DE"
ecoli_us$Location[ecoli_us$Location %like% "Delaware" == TRUE] <- "DE"
ecoli_us$Location[ecoli_us$Location %like% "TX" == TRUE] <- "TX"
ecoli_us$Location[ecoli_us$Location %like% "Texas" == TRUE] <- "TX"
ecoli_us$Location[ecoli_us$Location %like% "USA:WA" == TRUE] <- "WA"
ecoli_us$Location[ecoli_us$Location %like% "USA: WA" == TRUE] <- "WA"
ecoli_us$Location[ecoli_us$Location %like% "Washington" == TRUE] <- "WA"
ecoli_us$Location[ecoli_us$Location %like% "USA:OH" == TRUE] <- "OH"
ecoli_us$Location[ecoli_us$Location %like% "USA: OH" == TRUE] <- "OH"
ecoli_us$Location[ecoli_us$Location %like% "Ohio" == TRUE] <-"OH"
ecoli_us$Location[ecoli_us$Location %like% "USA:WI" == TRUE] <- "WI"
ecoli_us$Location[ecoli_us$Location %like% "USA: WI" == TRUE] <- "WI"
ecoli_us$Location[ecoli_us$Location %like% "Wisconsin" == TRUE] <- "WI"
ecoli_us$Location[ecoli_us$Location %like% "USA:KY" == TRUE] <- "KY"
ecoli_us$Location[ecoli_us$Location %like% "USA: KY" == TRUE] <- "KY"
ecoli_us$Location[ecoli_us$Location %like% "Kentucky" == TRUE] <- "KY"
ecoli_us$Location[ecoli_us$Location %like% "USA:MD" == TRUE] <- "MD"
ecoli_us$Location[ecoli_us$Location %like% "USA: MD" == TRUE] <- "MD"
ecoli_us$Location[ecoli_us$Location %like% "AZ" == TRUE] <- "AZ"
ecoli_us$Location[ecoli_us$Location %like% "Arizona" == TRUE] <- "AZ"
ecoli_us$Location[ecoli_us$Location %like% "USA:MI" == TRUE] <- "MI"
ecoli_us$Location[ecoli_us$Location %like% "USA: MI" == TRUE] <- "MI"
ecoli_us$Location[ecoli_us$Location %like% "USA:Mi" == TRUE] <- "MI"
ecoli_us$Location[ecoli_us$Location %like% "Michigan" == TRUE] <- "MI"
ecoli_us$Location[ecoli_us$Location %like% "USA:FL" == TRUE] <- "FL"
ecoli_us$Location[ecoli_us$Location %like% "USA: FL" == TRUE] <- "FL"
ecoli_us$Location[ecoli_us$Location %like% "Florida" == TRUE] <- "FL"
ecoli_us$Location[ecoli_us$Location %like% "NJ" == TRUE] <- "NJ"
ecoli_us$Location[ecoli_us$Location %like% "New Jersey" == TRUE] <- "NJ"
ecoli_us$Location[ecoli_us$Location %like% "New Jersy" == TRUE] <- "NJ"
ecoli_us$Location[ecoli_us$Location %like% "USA:IN" == TRUE] <- "IN"
ecoli_us$Location[ecoli_us$Location %like% "USA: IN" == TRUE] <- "IN"
ecoli_us$Location[ecoli_us$Location %like% "Indiana" == TRUE] <- "IN"
ecoli_us$Location[ecoli_us$Location %like% "USA:MA" == TRUE] <- "MA"
ecoli_us$Location[ecoli_us$Location %like% "USA: MA" == TRUE] <- "MA"
ecoli_us$Location[ecoli_us$Location %like% "Boston" == TRUE] <- "MA"
ecoli_us$Location[ecoli_us$Location %like% "Massachusetts" == TRUE] <- "MA"
ecoli_us$Location[ecoli_us$Location %like% "Maryland" == TRUE] <- "MA"
ecoli_us$Location[ecoli_us$Location %like% "USA:NY" == TRUE] <- "NY"
ecoli_us$Location[ecoli_us$Location %like% "USA: NY" == TRUE] <- "NY"
ecoli_us$Location[ecoli_us$Location %like% "New York" == TRUE] <- "NY"
ecoli_us$Location[ecoli_us$Location %like% "OK" == TRUE] <- "OK"
ecoli_us$Location[ecoli_us$Location %like% "Oklahoma" == TRUE] <- "OK"
ecoli_us$Location[ecoli_us$Location %like% "USA: NE" == TRUE] <- "NE"
ecoli_us$Location[ecoli_us$Location %like% "USA:NE" == TRUE] <- "NE"
ecoli_us$Location[ecoli_us$Location %like% "Nebraska" == TRUE] <- "NE"
ecoli_us$Location[ecoli_us$Location %like% "WV" == TRUE] <- "WV"
ecoli_us$Location[ecoli_us$Location %like% "UT" == TRUE] <- "UT"
ecoli_us$Location[ecoli_us$Location %like% "USA:IL" == TRUE] <- "IL"
ecoli_us$Location[ecoli_us$Location %like% "USA: IL" == TRUE] <- "IL"
ecoli_us$Location[ecoli_us$Location %like% "Illinois" == TRUE] <- "IL"
ecoli_us$Location[ecoli_us$Location %like% "KS" == TRUE] <- "KS"
ecoli_us$Location[ecoli_us$Location %like% "Kansas" == TRUE] <- "KS"
ecoli_us$Location[ecoli_us$Location %like% "MO" == TRUE] <- "MO"
ecoli_us$Location[ecoli_us$Location %like% "Missouri" == TRUE] <- "MO"
ecoli_us$Location[ecoli_us$Location %like% "USA:RI" == TRUE] <- "RI"
ecoli_us$Location[ecoli_us$Location %like% "USA: RI" == TRUE] <- "RI"
ecoli_us$Location[ecoli_us$Location %like% "USA: ID" == TRUE] <- "ID"
ecoli_us$Location[ecoli_us$Location %like% "USA:ID" == TRUE] <- "ID"
ecoli_us$Location[ecoli_us$Location %like% "USA:AR" == TRUE] <- "AR"
ecoli_us$Location[ecoli_us$Location %like% "USA: AR" == TRUE] <- "AR"
ecoli_us$Location[ecoli_us$Location %like% "Arkansas" == TRUE] <- "AR"
ecoli_us$Location[ecoli_us$Location %like% "USA:MN" == TRUE] <- "MN"
ecoli_us$Location[ecoli_us$Location %like% "USA: MN" == TRUE] <- "MN"
ecoli_us$Location[ecoli_us$Location %like% "Minnesota" == TRUE] <- "MS"
ecoli_us$Location[ecoli_us$Location %like% "Minneapolis" == TRUE] <- "MS"
ecoli_us$Location[ecoli_us$Location %like% "USA:LA" == TRUE] <- "LA"
ecoli_us$Location[ecoli_us$Location %like% "USA: LA" == TRUE] <- "LA"
ecoli_us$Location[ecoli_us$Location %like% "Louisiana" == TRUE] <- "LA"
ecoli_us$Location[ecoli_us$Location %like% "USA:NM" == TRUE] <- "NM"
ecoli_us$Location[ecoli_us$Location %like% "USA: NM" == TRUE] <- "NM"
ecoli_us$Location[ecoli_us$Location %like% "USA:AL" == TRUE] <- "AL"
ecoli_us$Location[ecoli_us$Location %like% "USA:ME" == TRUE] <- "ME"
ecoli_us$Location[ecoli_us$Location %like% "USA: ME" == TRUE] <- "ME"
ecoli_us$Location[ecoli_us$Location %like% "Maine" == TRUE] <- "ME"
ecoli_us$Location[ecoli_us$Location %like% "VT" == TRUE] <- "VT"
ecoli_us$Location[ecoli_us$Location %like% "USA: HI" == TRUE] <- "HI"
ecoli_us$Location[ecoli_us$Location %like% "USA:HI" == TRUE] <- "HI"
ecoli_us$Location[ecoli_us$Location %like% "USA:CT" == TRUE] <- "CT"
ecoli_us$Location[ecoli_us$Location %like% "USA: CT" == TRUE] <- "CT"
ecoli_us$Location[ecoli_us$Location %like% "Connecticut" == TRUE] <- "CT"
ecoli_us$Location[ecoli_us$Location %like% "USA:PR" == TRUE] <- "PR"
ecoli_us$Location[ecoli_us$Location %like% "USA:ND" == TRUE] <- "ND"
ecoli_us$Location[ecoli_us$Location %like% "USA: ND" == TRUE] <- "ND"
ecoli_us$Location[ecoli_us$Location %like% "North Dakota" == TRUE] <- "ND"
ecoli_us$Location[ecoli_us$Location %like% "USA:OR" == TRUE] <- "OR"
ecoli_us$Location[ecoli_us$Location %like% "USA: OR" == TRUE] <- "OR"
ecoli_us$Location[ecoli_us$Location %like% "USA: or" == TRUE] <- "OR"
ecoli_us$Location[ecoli_us$Location %like% "USA:or" == TRUE] <- "OR"
ecoli_us$Location[ecoli_us$Location %like% "Oregon" == TRUE] <- "OR"
ecoli_us$Location[ecoli_us$Location %like% "USA:NH" == TRUE] <- "NH"
ecoli_us$Location[ecoli_us$Location %like% "USA: NH" == TRUE] <- "NH"
ecoli_us$Location[ecoli_us$Location %like% "New Hampshire" == TRUE] <- "NH"
ecoli_us$Location[ecoli_us$Location %like% "USA:WY" == TRUE] <- "WY"
ecoli_us$Location[ecoli_us$Location %like% "USA: WY" == TRUE] <- "WY"
ecoli_us$Location[ecoli_us$Location %like% "NV" == TRUE] <- "NV"
ecoli_us$Location[ecoli_us$Location %like% "USA:DC" == TRUE] <- "DC"
ecoli_us$Location[ecoli_us$Location %like% "USA: Washington DC" == TRUE] <- "DC"
ecoli_us$Location[ecoli_us$Location %like% "USA:State" == TRUE] <- "DC"
ecoli_us$Location[ecoli_us$Location %like% "Midwest" == TRUE] <- "Midwest"
ecoli_us$Location[ecoli_us$Location %like% "MidWest" == TRUE] <- "Midwest"
ecoli_us$Location[ecoli_us$Location %like% "USA:AK" == TRUE] <- "AK"
ecoli_us$Location[ecoli_us$Location %like% "USA:MT" == TRUE] <- "MT"
ecoli_us$Location[ecoli_us$Location %like% "USA:MW" == TRUE] <- "MW"
ecoli_us$Location[ecoli_us$Location %like% "Lansing" == TRUE] <- "MI"
ecoli_us$Location[ecoli_us$Location %like% "Gainesville" == TRUE] <- "FL"
ecoli_us$Location[ecoli_us$Location %like% "Tulsa" == TRUE] <- "OK"
ecoli_us$Location[ecoli_us$Location %like% "Western Region" == TRUE] <- "Western Region"
ecoli_us$Location[ecoli_us$Location %like% "region 9" == TRUE] <- "HHS region 9"
ecoli_us$Location[ecoli_us$Location %like% "Chicago" == TRUE] <- "IL"
ecoli_us$Location[ecoli_us$Location %like% ", CA" == TRUE] <- "CA"
ecoli_us$Location[ecoli_us$Location %like% ", NY" == TRUE] <- "NY"
ecoli_us$Location[ecoli_us$Location %like% ", CO" == TRUE] <- "CO"

ecoli_us$Location[ecoli_us$Location %like% ", NC" == TRUE] <- "NC"
ecoli_us$Location[ecoli_us$Location %like% "Bethesda" == TRUE] <- "MD"
ecoli_us$Location[ecoli_us$Location %like% "District of Columbia" == TRUE] <- "DC"
ecoli_us$Location[ecoli_us$Location %like% "Alaska" == TRUE] <- "AK"
ecoli_us$Location[ecoli_us$Location %like% "St. Louis" == TRUE] <- "MO"
ecoli_us$Location[ecoli_us$Location %like% "Utah" == TRUE] <- "UT"
ecoli_us$Location[ecoli_us$Location %like% "Houston" == TRUE] <- "TX"
ecoli_us$Location[ecoli_us$Location %like% "Tennessee" == TRUE] <- "TN"
ecoli_us$Location[ecoli_us$Location %like% "Califronia" == TRUE] <- "CA"
ecoli_us$Location[ecoli_us$Location %like% "Baltimore" == TRUE] <- "MD"
ecoli_us$Location[ecoli_us$Location %like% "Seattle" == TRUE] <- "WA"
ecoli_us$Location[ecoli_us$Location %like% ", MN" == TRUE] <- "MN"
ecoli_us$Location[ecoli_us$Location %like% ", WI" == TRUE] <- "WI"
ecoli_us$Location[ecoli_us$Location %like% ", OH" == TRUE] <- "OH"
ecoli_us$Location[ecoli_us$Location %like% ", IL" == TRUE] <- "IL"
ecoli_us$Location[ecoli_us$Location %like% ", MD" == TRUE] <- "MD"
ecoli_us$Location[ecoli_us$Location %like% ", IN" == TRUE] <- "IN"
ecoli_us$Location[ecoli_us$Location %like% ", NE" == TRUE] <- "NE"
ecoli_us$Location[ecoli_us$Location %like% ", FL" == TRUE] <- "FL"
ecoli_us$Location[ecoli_us$Location %like% ", MA" == TRUE] <- "MA"
ecoli_us$Location[ecoli_us$Location %like% ",WA" == TRUE] <- "WA"
ecoli_us$Location[ecoli_us$Location %like% "USA: DC" == TRUE] <- "DC"
ecoli_us$Location[ecoli_us$Location %like% "Ann Arbor" == TRUE] <- "MI"
ecoli_us$Location[ecoli_us$Location %like% "Los Angeles" == TRUE] <- "CA"
ecoli_us$Location[ecoli_us$Location %like% "Atlanta" == TRUE] <- "GA"
ecoli_us$Location[ecoli_us$Location %like% ", ID" == TRUE] <- "ID"
ecoli_us$Location[ecoli_us$Location %like% "UCLA" == TRUE] <- "CA"
ecoli_us$Location[ecoli_us$Location %like% ", MI" == TRUE] <- "MI"
ecoli_us$Location[ecoli_us$Location %like% "St Louis" == TRUE] <- "MO"
ecoli_us$Location[ecoli_us$Location %like% "UCSB" == TRUE] <- "CA"
ecoli_us$Location[ecoli_us$Location %like% "Rhode" == TRUE] <- "RI"
ecoli_us$Location[ecoli_us$Location %like% ", WI" == TRUE] <- "WI"
ecoli_us$Location[ecoli_us$Location %like% "South Dakota" == TRUE] <- "SD"
ecoli_us$Location[ecoli_us$Location %like% "Sacramento" == TRUE] <- "CA"
ecoli_us$Location[ecoli_us$Location %like% "Montana" == TRUE] <- "MT"
ecoli_us$Location[ecoli_us$Location %like% "South Central" == TRUE] <- "South Central"
ecoli_us$Location[ecoli_us$Location %like% "USA:West" == TRUE] <- "West"
ecoli_us$Location[ecoli_us$Location %like% "Montana" == TRUE] <- "MT"
ecoli_us$Location[ecoli_us$Location %like% "Nevada" == TRUE] <- "NV"
ecoli_us$Location[ecoli_us$Location %like% "New Mexico" == TRUE] <- "NM"
ecoli_us$Location[ecoli_us$Location %like% "USA: South" == TRUE] <- "South"
ecoli_us$Location[ecoli_us$Location %like% "USA: West" == TRUE] <- "West"
ecoli_us$Location[ecoli_us$Location %like% "Pittsburgh" == TRUE] <- "PA"
ecoli_us$Location[ecoli_us$Location %like% "Pacific Northwest" == TRUE] <- "Pacific Northwest"
ecoli_us$Location[ecoli_us$Location %like% "Miami" == TRUE] <- "FL"
ecoli_us$Location[ecoli_us$Location %like% "Cincinnati" == TRUE] <- "OH"
ecoli_us$Location[ecoli_us$Location %like% "Palo Alto" == TRUE] <- "CA"
ecoli_us$Location[ecoli_us$Location %like% "Alachua" == TRUE] <- "FL"
ecoli_us$Location[ecoli_us$Location %like% "Menlo Park" == TRUE] <- "CA"
ecoli_us$Location[ecoli_us$Location %like% "Lahey Hospital" == TRUE] <- "MA"
ecoli_us$Location[ecoli_us$Location %like% "midwest" == TRUE] <- "Midwest"
ecoli_us$Location[ecoli_us$Location %like% "USA: West" == TRUE] <- "West"
ecoli_us$Location[ecoli_us$Location %like% "Northeast" == TRUE] <- "Northeast"
ecoli_us$Location[ecoli_us$Location %like% "Wood Johnson" == TRUE] <- "NJ"
ecoli_us$Location[ecoli_us$Location %like% "Western States" == TRUE] <- "West"
ecoli_us$Location[ecoli_us$Location %like% "Walnut Creek" == TRUE] <- "CA"
ecoli_us$Location[ecoli_us$Location %like% "Idaho" == TRUE] <- "ID"
ecoli_us$Location[ecoli_us$Location %like% "San Antonio" == TRUE] <- "TX"
ecoli_us$Location[ecoli_us$Location %like% "Caguas" == TRUE] <- "PR"
ecoli_us$Location[ecoli_us$Location %like% "Burlington" == TRUE] <- "VT"
ecoli_us$Location[ecoli_us$Location %like% "Milwaukee" == TRUE] <- "WI"
ecoli_us$Location[ecoli_us$Location %like% "Lafayette" == TRUE] <- "LA"
ecoli_us$Location[ecoli_us$Location %like% "Cambridge" == TRUE] <- "MA"
ecoli_us$Location[ecoli_us$Location %like% "Moscow" == TRUE] <- "ID"


unique(sal_us$Location)
