## This is a code for PHP 2550 at Brown University SPH, the purpose is to 
## clean location that have different format e.g some are two letters state
## abbreviation, some are full state names or some are the big cities name
## without the state name. To account for this heterogenity, we preprocess
## the data here.

library(data.table)

#load the data
sal_dat <- read.csv("salmonella_2013to2022.csv")

dim(sal_dat) # 194239     21

#extract only US cases
sal_us <- sal_dat[sal_dat$Location %like% "US", ]
dim(sal_us) #93763    21
names(which(colSums(is.na(sal_us)) > 0))

#clean for location
sal_us$Location[sal_us$Location %like% "USA:NC"== TRUE] <- "NC"
sal_us$Location[sal_us$Location %like% "USA: NC"== TRUE] <- "NC"
sal_us$Location[sal_us$Location %like% "North Carolina"== TRUE] <- "NC"
sal_us$Location[sal_us$Location %like% "PA"== TRUE] <- "PA"
sal_us$Location[sal_us$Location %like% "Philadelphia" == TRUE] <- "PA"
sal_us$Location[sal_us$Location %like% "Pennsylvania" == TRUE] <- "PA"
sal_us$Location[sal_us$Location %like% "GA" == TRUE] <- "GA"
sal_us$Location[sal_us$Location %like% "Georgia" == TRUE] <- "GA"
sal_us$Location[sal_us$Location %like% "USA:AL" == TRUE] <- "AL"
sal_us$Location[sal_us$Location %like% "USA: AL" == TRUE] <- "AL"
sal_us$Location[sal_us$Location %like% "Alabama" == TRUE] <- "AL"
sal_us$Location[sal_us$Location %like% "SC" == TRUE] <- "SC"
sal_us$Location[sal_us$Location %like% "SD" == TRUE] <- "SD"
sal_us$Location[sal_us$Location %like% "IA" == TRUE] <- "IA"
sal_us$Location[sal_us$Location %like% "Iowa" == TRUE] <- "IA"
sal_us$Location[sal_us$Location %like% "TN" == TRUE] <- "TN"
sal_us$Location[sal_us$Location %like% "USA:CO" == TRUE] <- "CO"
sal_us$Location[sal_us$Location %like% "USA: CO" == TRUE] <- "CO"
sal_us$Location[sal_us$Location %like% "USA: Aurora, CO" == TRUE] <- "CO"
sal_us$Location[sal_us$Location %like% "Colorado" == TRUE] <- "CO"
sal_us$Location[sal_us$Location %like% "MS" == TRUE] <- "MS"
sal_us$Location[sal_us$Location %like% "Mississippi" == TRUE] <- "MS"
sal_us$Location[sal_us$Location %like% "USA: CA" == TRUE] <- "CA"
sal_us$Location[sal_us$Location %like% "USA:CA" == TRUE] <- "CA"
sal_us$Location[sal_us$Location %like% "San Diego" == TRUE] <- "CA"
sal_us$Location[sal_us$Location %like% "San Francisco" == TRUE] <- "CA"
sal_us$Location[sal_us$Location %like% "California" == TRUE] <- "CA"
sal_us$Location[sal_us$Location %like% "Davis" == TRUE] <- "CA"
sal_us$Location[sal_us$Location %like% "USA:GU" == TRUE] <- "GU"
sal_us$Location[sal_us$Location %like% "VA" == TRUE] <- "VA"
sal_us$Location[sal_us$Location %like% "Virginia" == TRUE] <- "VA"
sal_us$Location[sal_us$Location %like% "USA:DE" == TRUE] <- "DE"
sal_us$Location[sal_us$Location %like% "Delaware" == TRUE] <- "DE"
sal_us$Location[sal_us$Location %like% "TX" == TRUE] <- "TX"
sal_us$Location[sal_us$Location %like% "Texas" == TRUE] <- "TX"
sal_us$Location[sal_us$Location %like% "USA:WA" == TRUE] <- "WA"
sal_us$Location[sal_us$Location %like% "USA: WA" == TRUE] <- "WA"
sal_us$Location[sal_us$Location %like% "Washington" == TRUE] <- "WA"
sal_us$Location[sal_us$Location %like% "USA:OH" == TRUE] <- "OH"
sal_us$Location[sal_us$Location %like% "USA: OH" == TRUE] <- "OH"
sal_us$Location[sal_us$Location %like% "Ohio" == TRUE] <-"OH"
sal_us$Location[sal_us$Location %like% "USA:WI" == TRUE] <- "WI"
sal_us$Location[sal_us$Location %like% "USA: WI" == TRUE] <- "WI"
sal_us$Location[sal_us$Location %like% "Wisconsin" == TRUE] <- "WI"
sal_us$Location[sal_us$Location %like% "USA:KY" == TRUE] <- "KY"
sal_us$Location[sal_us$Location %like% "USA: KY" == TRUE] <- "KY"
sal_us$Location[sal_us$Location %like% "Kentucky" == TRUE] <- "KY"
sal_us$Location[sal_us$Location %like% "USA:MD" == TRUE] <- "MD"
sal_us$Location[sal_us$Location %like% "USA: MD" == TRUE] <- "MD"
sal_us$Location[sal_us$Location %like% "AZ" == TRUE] <- "AZ"
sal_us$Location[sal_us$Location %like% "Arizona" == TRUE] <- "AZ"
sal_us$Location[sal_us$Location %like% "USA:MI" == TRUE] <- "MI"
sal_us$Location[sal_us$Location %like% "USA: MI" == TRUE] <- "MI"
sal_us$Location[sal_us$Location %like% "USA:Mi" == TRUE] <- "MI"
sal_us$Location[sal_us$Location %like% "Michigan" == TRUE] <- "MI"
sal_us$Location[sal_us$Location %like% "USA:FL" == TRUE] <- "FL"
sal_us$Location[sal_us$Location %like% "USA: FL" == TRUE] <- "FL"
sal_us$Location[sal_us$Location %like% "Florida" == TRUE] <- "FL"
sal_us$Location[sal_us$Location %like% "NJ" == TRUE] <- "NJ"
sal_us$Location[sal_us$Location %like% "New Jersey" == TRUE] <- "NJ"
sal_us$Location[sal_us$Location %like% "New Jersy" == TRUE] <- "NJ"
sal_us$Location[sal_us$Location %like% "USA:IN" == TRUE] <- "IN"
sal_us$Location[sal_us$Location %like% "USA: IN" == TRUE] <- "IN"
sal_us$Location[sal_us$Location %like% "Indiana" == TRUE] <- "IN"
sal_us$Location[sal_us$Location %like% "USA:MA" == TRUE] <- "MA"
sal_us$Location[sal_us$Location %like% "USA: MA" == TRUE] <- "MA"
sal_us$Location[sal_us$Location %like% "Boston" == TRUE] <- "MA"
sal_us$Location[sal_us$Location %like% "Massachusetts" == TRUE] <- "MA"
sal_us$Location[sal_us$Location %like% "Maryland" == TRUE] <- "MA"
sal_us$Location[sal_us$Location %like% "USA:NY" == TRUE] <- "NY"
sal_us$Location[sal_us$Location %like% "USA: NY" == TRUE] <- "NY"
sal_us$Location[sal_us$Location %like% "New York" == TRUE] <- "NY"
sal_us$Location[sal_us$Location %like% "OK" == TRUE] <- "OK"
sal_us$Location[sal_us$Location %like% "Oklahoma" == TRUE] <- "OK"
sal_us$Location[sal_us$Location %like% "USA: NE" == TRUE] <- "NE"
sal_us$Location[sal_us$Location %like% "USA:NE" == TRUE] <- "NE"
sal_us$Location[sal_us$Location %like% "Nebraska" == TRUE] <- "NE"
sal_us$Location[sal_us$Location %like% "WV" == TRUE] <- "WV"
sal_us$Location[sal_us$Location %like% "UT" == TRUE] <- "UT"
sal_us$Location[sal_us$Location %like% "USA:IL" == TRUE] <- "IL"
sal_us$Location[sal_us$Location %like% "USA: IL" == TRUE] <- "IL"
sal_us$Location[sal_us$Location %like% "Illinois" == TRUE] <- "IL"
sal_us$Location[sal_us$Location %like% "KS" == TRUE] <- "KS"
sal_us$Location[sal_us$Location %like% "Kansas" == TRUE] <- "KS"
sal_us$Location[sal_us$Location %like% "MO" == TRUE] <- "MO"
sal_us$Location[sal_us$Location %like% "Missouri" == TRUE] <- "MO"
sal_us$Location[sal_us$Location %like% "USA:RI" == TRUE] <- "RI"
sal_us$Location[sal_us$Location %like% "USA: RI" == TRUE] <- "RI"
sal_us$Location[sal_us$Location %like% "USA: ID" == TRUE] <- "ID"
sal_us$Location[sal_us$Location %like% "USA:ID" == TRUE] <- "ID"
sal_us$Location[sal_us$Location %like% "USA:AR" == TRUE] <- "AR"
sal_us$Location[sal_us$Location %like% "USA: AR" == TRUE] <- "AR"
sal_us$Location[sal_us$Location %like% "Arkansas" == TRUE] <- "AR"
sal_us$Location[sal_us$Location %like% "USA:MN" == TRUE] <- "MN"
sal_us$Location[sal_us$Location %like% "USA: MN" == TRUE] <- "MN"
sal_us$Location[sal_us$Location %like% "Minnesota" == TRUE] <- "MS"
sal_us$Location[sal_us$Location %like% "Minneapolis" == TRUE] <- "MS"
sal_us$Location[sal_us$Location %like% "USA:LA" == TRUE] <- "LA"
sal_us$Location[sal_us$Location %like% "USA: LA" == TRUE] <- "LA"
sal_us$Location[sal_us$Location %like% "Louisiana" == TRUE] <- "LA"
sal_us$Location[sal_us$Location %like% "USA:NM" == TRUE] <- "NM"
sal_us$Location[sal_us$Location %like% "USA: NM" == TRUE] <- "NM"
sal_us$Location[sal_us$Location %like% "USA:AL" == TRUE] <- "AL"
sal_us$Location[sal_us$Location %like% "USA:ME" == TRUE] <- "ME"
sal_us$Location[sal_us$Location %like% "USA: ME" == TRUE] <- "ME"
sal_us$Location[sal_us$Location %like% "Maine" == TRUE] <- "ME"
sal_us$Location[sal_us$Location %like% "VT" == TRUE] <- "VT"
sal_us$Location[sal_us$Location %like% "USA: HI" == TRUE] <- "HI"
sal_us$Location[sal_us$Location %like% "USA:HI" == TRUE] <- "HI"
sal_us$Location[sal_us$Location %like% "USA:CT" == TRUE] <- "CT"
sal_us$Location[sal_us$Location %like% "USA: CT" == TRUE] <- "CT"
sal_us$Location[sal_us$Location %like% "Connecticut" == TRUE] <- "CT"
sal_us$Location[sal_us$Location %like% "USA:PR" == TRUE] <- "PR"
sal_us$Location[sal_us$Location %like% "USA:ND" == TRUE] <- "ND"
sal_us$Location[sal_us$Location %like% "USA: ND" == TRUE] <- "ND"
sal_us$Location[sal_us$Location %like% "North Dakota" == TRUE] <- "ND"
sal_us$Location[sal_us$Location %like% "USA:OR" == TRUE] <- "OR"
sal_us$Location[sal_us$Location %like% "USA: OR" == TRUE] <- "OR"
sal_us$Location[sal_us$Location %like% "USA: or" == TRUE] <- "OR"
sal_us$Location[sal_us$Location %like% "USA:or" == TRUE] <- "OR"
sal_us$Location[sal_us$Location %like% "Oregon" == TRUE] <- "OR"
sal_us$Location[sal_us$Location %like% "USA:NH" == TRUE] <- "NH"
sal_us$Location[sal_us$Location %like% "USA: NH" == TRUE] <- "NH"
sal_us$Location[sal_us$Location %like% "New Hampshire" == TRUE] <- "NH"
sal_us$Location[sal_us$Location %like% "USA:WY" == TRUE] <- "WY"
sal_us$Location[sal_us$Location %like% "USA: WY" == TRUE] <- "WY"
sal_us$Location[sal_us$Location %like% "NV" == TRUE] <- "NV"
sal_us$Location[sal_us$Location %like% "USA:DC" == TRUE] <- "DC"
sal_us$Location[sal_us$Location %like% "USA: Washington DC" == TRUE] <- "DC"
sal_us$Location[sal_us$Location %like% "USA:State" == TRUE] <- "DC"
sal_us$Location[sal_us$Location %like% "Midwest" == TRUE] <- "Midwest"
sal_us$Location[sal_us$Location %like% "MidWest" == TRUE] <- "Midwest"
sal_us$Location[sal_us$Location %like% "USA:AK" == TRUE] <- "AK"
sal_us$Location[sal_us$Location %like% "USA:MT" == TRUE] <- "MT"
sal_us$Location[sal_us$Location %like% "USA:MW" == TRUE] <- "MW"
sal_us$Location[sal_us$Location %like% "Lansing" == TRUE] <- "MI"
sal_us$Location[sal_us$Location %like% "Gainesville" == TRUE] <- "FL"
sal_us$Location[sal_us$Location %like% "Tulsa" == TRUE] <- "OK"
sal_us$Location[sal_us$Location %like% "Western Region" == TRUE] <- "Western Region"
sal_us$Location[sal_us$Location %like% "region 9" == TRUE] <- "HHS region 9"

unique(sal_us$Location)

